package com.example.lumina.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single journal entry stored in the local database.
 *
 * @property id The unique identifier for the journal entry, auto-generated by Room.
 * @property title The headline or subject of the entry.
 * @property content The main body text of the journal entry.
 * @property date The creation or occurrence time of the entry, stored as a Unix timestamp.
 * @property mood The emotional state associated with this entry.
 */
@Entity(tableName = "journal_entries")
data class JournalEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val content: String,
    val date: Long, // Store as timestamp
    val mood: Mood
)
